# Generated by Django 4.2 on 2023-05-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
